server:
  port: 8080

proxy:
  host: http://localhost:8088/

spring:
  jpa:
    database-platform: ch.awae.moba2.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:sqlite:persistence.db
    driver-class-name: org.sqlite.JDBC

control:
  path-store:
    save-timeout: 5000

