server:
  port: 8080

proxy:
  host: http://192.168.1.201:8088/

app:
  artifactId: @project.artifactId@
  version: @project.version@_@buildNumber@

spring:
  jpa:
    open-in-view: false
    database-platform: ch.awae.moba2.core.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: jdbc:sqlite:persistence.db
    driver-class-name: org.sqlite.JDBC

processor:
  path-store:
    save-timeout: 5000

provider:
  button: buttons.yml
  light: lights.yml
  path: paths.yml
